"""Module 9 Component 6 — AI Timesheet Reconciliation schema

Creates:
  timesheet_sessions  — one row per reconciliation run (date range, sources used)
  timesheet_drafts    — one row per draft time entry generated by AI

The reconciliation engine ingests uploaded files (Excel timesheets,
phone carrier CSV, ManicTime exports, flat files) plus pulls from
ai_api_calls and ts_slips, then uses AI to cross-reference all sources
against matter summaries and generate draft entries with confidence scores.
Attorney reviews, approves, edits, and pushes approved entries to time_entries.

Revision ID: 0015_m9_timesheet
Revises: 0014_m9_crawl_jobs
Create Date: 2026-03-31

Patent Pending — 64/020,027 — Dennis M. Holmgren, Reg. No. 54,168
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision = "0015_m9_timesheet"
down_revision = "0014_m9_crawl_jobs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # ── timesheet_sessions ────────────────────────────────────────────────────
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS timesheet_sessions (
            id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text,
            tenant_id VARCHAR(36) NOT NULL,
            user_id BIGINT NOT NULL,
            date_from DATE NOT NULL,
            date_to DATE NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'running',
            sources_used JSONB NOT NULL DEFAULT '[]',
            uploaded_files JSONB NOT NULL DEFAULT '[]',
            draft_count INTEGER NOT NULL DEFAULT 0,
            approved_count INTEGER NOT NULL DEFAULT 0,
            pushed_count INTEGER NOT NULL DEFAULT 0,
            error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            completed_at TIMESTAMPTZ,
            CONSTRAINT ck_ts_sessions_status
                CHECK (status IN ('running','complete','failed','partial'))
        )
    """))

    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_sessions_tenant_user
        ON timesheet_sessions (tenant_id, user_id)
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_sessions_date_range
        ON timesheet_sessions (date_from, date_to)
    """))

    # ── timesheet_drafts ──────────────────────────────────────────────────────
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS timesheet_drafts (
            id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text,
            session_id TEXT NOT NULL REFERENCES timesheet_sessions(id) ON DELETE CASCADE,
            tenant_id VARCHAR(36) NOT NULL,
            user_id BIGINT NOT NULL,
            entry_date DATE NOT NULL,
            matter_id UUID,
            matter_name TEXT,
            hours NUMERIC(8,4),
            description TEXT,
            source VARCHAR(50) NOT NULL,
            source_detail JSONB NOT NULL DEFAULT '{}',
            ai_confidence NUMERIC(4,3),
            ai_narrative TEXT,
            ai_raw_response TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            reviewed_at TIMESTAMPTZ,
            reviewed_by BIGINT,
            time_entry_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_timesheet_drafts_status
                CHECK (status IN ('pending','approved','rejected','pushed','edited')),
            CONSTRAINT ck_timesheet_drafts_source
                CHECK (source IN (
                    'timeslips','ai_api_calls','phone_csv',
                    'manictime','excel','flat_file','glass_break','manual'
                ))
        )
    """))

    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_drafts_session
        ON timesheet_drafts (session_id)
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_drafts_tenant_user
        ON timesheet_drafts (tenant_id, user_id)
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_drafts_entry_date
        ON timesheet_drafts (entry_date)
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_timesheet_drafts_status
        ON timesheet_drafts (status)
    """))

    # Grant to app user
    conn.execute(sa.text(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON timesheet_sessions TO praesidium_db"
    ))
    conn.execute(sa.text(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON timesheet_drafts TO praesidium_db"
    ))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS timesheet_drafts"))
    conn.execute(sa.text("DROP TABLE IF EXISTS timesheet_sessions"))
