"""
infra/proxy/local_nginx.py
Praesidium Series 2.0 — Reverse Proxy Backend: Local Docker nginx

Used by:
  - The appliance (ships as a single all-in-one box with nginx in a
    sibling container).
  - On-prem multi-tenant test deployments (up to 3 tenants per the
    install scope).

NOT used by:
  - HJMM production (uses SshRprxBackend → 10.10.40.50).
  - Any deployment where nginx is not co-located with the worker host
    and reachable via the local Docker socket.

Operating model:
  - The worker container (where this code runs) has TWO bind mounts:
      /opt/praesidium-mcp/nginx/sites/      (rw — write vhost files here)
      /var/run/docker.sock                  (ro — signal nginx to reload)
  - The nginx container reads vhost files from the SAME host directory
    (mounted ro into /etc/nginx/sites-enabled/ inside that container).
  - Reload is `docker exec praesidium-nginx nginx -s reload` after a
    `nginx -t` validation pass.

Configuration via env vars (all have sane defaults):
  NGINX_SITES_HOST_DIR    /opt/praesidium-mcp/nginx/sites
  NGINX_CONTAINER_NAME    praesidium-nginx
  PROXY_LISTEN_IP         10.10.40.75    (DMZ NIC IP nginx binds to)

⚖  PATENT NOTICE: Patent Pending — 64/020,027
   Filed March 29, 2026 by Dennis M. Holmgren, Reg. No. 54,168
"""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import Final

log = logging.getLogger("praesidium.infra.proxy.local_nginx")


_VHOST_TEMPLATE: Final[str] = """\
# Praesidium tenant: {slug}
# Generated by jobs/proxy_provision.py — do not hand-edit; rerun the
# provisioning job to regenerate, or use the tenant admin to remove.

upstream praesidium_web_{slug_safe} {{
    server {upstream_host}:{upstream_port};
    keepalive 32;
}}

# HTTP -> HTTPS redirect
server {{
    listen      {listen_ip}:80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen      {listen_ip}:443 ssl http2;
    server_name {domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Long browser cache for static assets.
    location ~* \\.(?:css|js|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {{
        proxy_pass         http://praesidium_web_{slug_safe};
        proxy_http_version 1.1;
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }}

    # Dynamic FastAPI routes (HTMX + SSE).
    location / {{
        proxy_pass         http://praesidium_web_{slug_safe};
        proxy_http_version 1.1;

        proxy_set_header   Upgrade            $http_upgrade;
        proxy_set_header   Connection         $connection_upgrade;
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;

        client_max_body_size 500M;

        proxy_buffering          off;
        proxy_request_buffering  off;
        proxy_read_timeout       300s;
        proxy_send_timeout       300s;
        proxy_connect_timeout    10s;
    }}
}}
"""


class LocalNginxBackend:
    """Writes vhost files to a host directory and reloads nginx via docker exec.

    Construction reads env vars; no other configuration. Pass overrides
    explicitly only in tests.
    """

    def __init__(
        self,
        sites_dir: str | None = None,
        container_name: str | None = None,
        listen_ip: str | None = None,
    ) -> None:
        self.sites_dir = Path(
            sites_dir or os.environ.get(
                "NGINX_SITES_HOST_DIR", "/opt/praesidium-mcp/nginx/sites"
            )
        )
        self.container_name = container_name or os.environ.get(
            "NGINX_CONTAINER_NAME", "praesidium-nginx"
        )
        self.listen_ip = listen_ip or os.environ.get(
            "PROXY_LISTEN_IP", "10.10.40.75"
        )

    # ── ProxyBackend protocol ────────────────────────────────────────────

    def write_vhost(
        self,
        slug: str,
        domain: str,
        ssl_mode: str,
        cert_path: str,
        key_path: str,
        upstream_host: str,
        upstream_port: int,
    ) -> tuple[bool, str]:
        slug_safe = _slug_for_nginx_var(slug)
        config = _VHOST_TEMPLATE.format(
            slug=slug,
            slug_safe=slug_safe,
            domain=domain,
            listen_ip=self.listen_ip,
            cert_path=cert_path,
            key_path=key_path,
            upstream_host=upstream_host,
            upstream_port=upstream_port,
        )

        target = self.sites_dir / f"{slug}.conf"
        try:
            self.sites_dir.mkdir(parents=True, exist_ok=True)
            # Write atomically: write to temp, fsync, rename.
            tmp = target.with_suffix(".conf.tmp")
            tmp.write_text(config, encoding="utf-8")
            tmp.replace(target)
            log.info("LocalNginxBackend.write_vhost: wrote %s (%d bytes)",
                     target, len(config))
            return True, f"vhost written to {target}"
        except OSError as exc:
            return False, f"failed to write vhost {target}: {exc}"

    def remove_vhost(self, slug: str) -> tuple[bool, str]:
        target = self.sites_dir / f"{slug}.conf"
        try:
            if target.exists():
                target.unlink()
                log.info("LocalNginxBackend.remove_vhost: removed %s", target)
                return True, f"removed {target}"
            return True, "vhost did not exist (no-op)"
        except OSError as exc:
            return False, f"failed to remove vhost {target}: {exc}"

    def reload(self) -> tuple[bool, str]:
        # Validate before reload — invalid configs blow up the running
        # nginx if we skip this and call -s reload directly.
        validate = self._docker_exec(["nginx", "-t"])
        if validate.returncode != 0:
            stderr = (validate.stderr or "").strip()
            log.error("LocalNginxBackend.reload: nginx -t failed: %s", stderr)
            return False, f"nginx -t failed: {stderr}"

        reload_proc = self._docker_exec(["nginx", "-s", "reload"])
        if reload_proc.returncode != 0:
            stderr = (reload_proc.stderr or "").strip()
            log.error("LocalNginxBackend.reload: nginx -s reload failed: %s",
                      stderr)
            return False, f"nginx reload failed: {stderr}"

        log.info("LocalNginxBackend.reload: ok")
        return True, "nginx reloaded"

    def health_check(self) -> tuple[bool, str]:
        # Two checks: container is running and nginx -t passes.
        inspect = subprocess.run(
            ["docker", "inspect", "--format", "{{.State.Running}}",
             self.container_name],
            capture_output=True, text=True, timeout=10,
        )
        if inspect.returncode != 0:
            return False, (
                f"container '{self.container_name}' not found "
                f"({(inspect.stderr or '').strip()})"
            )
        if (inspect.stdout or "").strip() != "true":
            return False, f"container '{self.container_name}' is not running"

        validate = self._docker_exec(["nginx", "-t"])
        if validate.returncode != 0:
            return False, (
                f"nginx -t failed in container: "
                f"{(validate.stderr or '').strip()}"
            )

        return True, f"container running, nginx -t ok"

    # ── Internals ────────────────────────────────────────────────────────

    def _docker_exec(self, cmd: list[str], timeout: int = 30):
        """Run a command inside the nginx container via the host Docker socket."""
        full = ["docker", "exec", self.container_name, *cmd]
        try:
            return subprocess.run(
                full, capture_output=True, text=True, timeout=timeout
            )
        except subprocess.TimeoutExpired:
            # Synthesize a CompletedProcess-like result so callers can
            # inspect returncode/stderr uniformly.
            class _Timeout:
                returncode = 124
                stdout = ""
                stderr = f"docker exec timed out after {timeout}s"
            return _Timeout()
        except FileNotFoundError:
            class _NoDocker:
                returncode = 127
                stdout = ""
                stderr = "docker binary not found in worker container PATH"
            return _NoDocker()


def _slug_for_nginx_var(slug: str) -> str:
    """nginx upstream identifiers cannot contain hyphens or other URL-safe
    characters that we permit in slugs. Replace with underscore.
    """
    return slug.replace("-", "_").replace(".", "_")
