"""
infra/proxy/ssh_rprx.py
Praesidium Series 2.0 — Reverse Proxy Backend: SSH to RPRX-01

Used by:
  - HJMM production (the praesidium-web container on WEB-01 cannot reach
    RPRX-01's nginx directly — it pushes vhost configs over SSH).

NOT used by:
  - The appliance (use LocalNginxBackend).
  - On-prem multi-tenant test installs (use LocalNginxBackend).

Operating model:
  - The worker writes the vhost to a temp path, then SSHes to
    praesidium@RPRX_HOST and `tee`s it into the sites-available dir,
    creates a symlink in sites-enabled, runs `nginx -t`, and reloads.
  - All commands are wrapped in `sudo` since nginx config is root-owned.
    The remote user must have NOPASSWD sudo for this narrow command set.
  - SSH host key verification is enforced; /etc/ssh/ssh_known_hosts on
    WEB-01 must contain RPRX-01's host key.

Configuration via env vars:
  RPRX_HOST                   IP/hostname of the RPRX server (default 10.10.40.50)
  RPRX_SSH_USER               Remote user (default praesidium)
  RPRX_SSH_KEY                Path to private key inside the worker container
                              (default /run/secrets/rprx_ssh_key)
  RPRX_NGINX_SITES_AVAILABLE  Default /etc/nginx/sites-available
  RPRX_NGINX_SITES_ENABLED    Default /etc/nginx/sites-enabled
  PROXY_LISTEN_IP             RPRX nginx listen IP, e.g. the public-facing one

⚖  PATENT NOTICE: Patent Pending — 64/020,027
   Filed March 29, 2026 by Dennis M. Holmgren, Reg. No. 54,168
"""

from __future__ import annotations

import logging
import os
import shlex
import subprocess
from typing import Final

log = logging.getLogger("praesidium.infra.proxy.ssh_rprx")


_VHOST_TEMPLATE: Final[str] = """\
# Praesidium tenant: {slug}
# Generated by jobs/proxy_provision.py — managed remotely; do not hand-edit.

upstream praesidium_web_{slug_safe} {{
    server {upstream_host}:{upstream_port};
    keepalive 32;
}}

server {{
    listen      80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen      443 ssl http2;
    server_name {domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 500M;

    location / {{
        proxy_pass         http://praesidium_web_{slug_safe};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade            $http_upgrade;
        proxy_set_header   Connection         "upgrade";
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }}
}}
"""


class SshRprxBackend:
    """Pushes vhost files to a remote RPRX nginx host over SSH."""

    def __init__(
        self,
        rprx_host: str | None = None,
        ssh_user: str | None = None,
        ssh_key: str | None = None,
        sites_available: str | None = None,
        sites_enabled: str | None = None,
    ) -> None:
        self.rprx_host = rprx_host or os.environ.get("RPRX_HOST", "10.10.40.50")
        self.ssh_user = ssh_user or os.environ.get("RPRX_SSH_USER", "praesidium")
        self.ssh_key = ssh_key or os.environ.get(
            "RPRX_SSH_KEY", "/run/secrets/rprx_ssh_key"
        )
        self.sites_available = sites_available or os.environ.get(
            "RPRX_NGINX_SITES_AVAILABLE", "/etc/nginx/sites-available"
        )
        self.sites_enabled = sites_enabled or os.environ.get(
            "RPRX_NGINX_SITES_ENABLED", "/etc/nginx/sites-enabled"
        )

    # ── ProxyBackend protocol ────────────────────────────────────────────

    def write_vhost(
        self,
        slug: str,
        domain: str,
        ssl_mode: str,
        cert_path: str,
        key_path: str,
        upstream_host: str,
        upstream_port: int,
    ) -> tuple[bool, str]:
        slug_safe = slug.replace("-", "_").replace(".", "_")
        config = _VHOST_TEMPLATE.format(
            slug=slug,
            slug_safe=slug_safe,
            domain=domain,
            cert_path=cert_path,
            key_path=key_path,
            upstream_host=upstream_host,
            upstream_port=upstream_port,
        )

        avail = f"{self.sites_available}/{slug}.conf"
        enabled = f"{self.sites_enabled}/{slug}.conf"

        # Single SSH session: tee + symlink. Reload is a separate call so
        # that batch operations (e.g. provisioning multiple tenants) can
        # write all configs and reload once at the end.
        remote_cmd = (
            f"sudo tee {shlex.quote(avail)} > /dev/null && "
            f"sudo ln -sf {shlex.quote(avail)} {shlex.quote(enabled)}"
        )
        proc = self._ssh(remote_cmd, stdin_data=config.encode())
        if proc.returncode != 0:
            return False, (
                f"remote tee/symlink failed (rc={proc.returncode}): "
                f"{(proc.stderr or '').strip()}"
            )
        log.info("SshRprxBackend.write_vhost: wrote %s on %s",
                 avail, self.rprx_host)
        return True, f"vhost written to {avail} on {self.rprx_host}"

    def remove_vhost(self, slug: str) -> tuple[bool, str]:
        avail = f"{self.sites_available}/{slug}.conf"
        enabled = f"{self.sites_enabled}/{slug}.conf"
        remote_cmd = (
            f"sudo rm -f {shlex.quote(avail)} {shlex.quote(enabled)}"
        )
        proc = self._ssh(remote_cmd)
        if proc.returncode != 0:
            return False, (
                f"remote rm failed (rc={proc.returncode}): "
                f"{(proc.stderr or '').strip()}"
            )
        log.info("SshRprxBackend.remove_vhost: removed %s, %s", avail, enabled)
        return True, "removed"

    def reload(self) -> tuple[bool, str]:
        # nginx -t before reload — see LocalNginxBackend for the same pattern.
        proc = self._ssh("sudo nginx -t")
        if proc.returncode != 0:
            return False, (
                f"remote nginx -t failed: {(proc.stderr or '').strip()}"
            )
        proc = self._ssh("sudo systemctl reload nginx")
        if proc.returncode != 0:
            return False, (
                f"remote systemctl reload nginx failed: "
                f"{(proc.stderr or '').strip()}"
            )
        log.info("SshRprxBackend.reload: ok on %s", self.rprx_host)
        return True, f"reloaded on {self.rprx_host}"

    def health_check(self) -> tuple[bool, str]:
        # SSH connectivity + nginx -t. No DNS check; if SSH works, the
        # host is reachable.
        proc = self._ssh("sudo nginx -t", timeout=10)
        if proc.returncode != 0:
            return False, (
                f"health check failed: {(proc.stderr or '').strip() or 'no stderr'}"
            )
        return True, f"ssh+nginx ok on {self.rprx_host}"

    # ── Internals ────────────────────────────────────────────────────────

    def _ssh(
        self,
        remote_cmd: str,
        stdin_data: bytes | None = None,
        timeout: int = 30,
    ):
        """Run a command on the remote host via SSH."""
        argv = [
            "ssh",
            "-o", "StrictHostKeyChecking=yes",
            "-o", "BatchMode=yes",
            "-o", f"ConnectTimeout={min(timeout, 10)}",
            "-i", self.ssh_key,
            f"{self.ssh_user}@{self.rprx_host}",
            remote_cmd,
        ]
        try:
            return subprocess.run(
                argv,
                input=stdin_data,
                capture_output=True,
                text=False if stdin_data is not None else True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            class _Timeout:
                returncode = 124
                stdout = b"" if stdin_data is not None else ""
                stderr = (
                    b"ssh timed out" if stdin_data is not None
                    else "ssh timed out"
                )
            return _Timeout()
        except FileNotFoundError:
            class _NoSsh:
                returncode = 127
                stdout = b"" if stdin_data is not None else ""
                stderr = (
                    b"ssh binary not found" if stdin_data is not None
                    else "ssh binary not found"
                )
            return _NoSsh()
