services:
  mail-corp:
    image: stalwartlabs/stalwart:latest
    container_name: praesidium-mail-corp
    restart: unless-stopped
    hostname: stalwart.praesidium.legal
    command: ["--config", "/etc/stalwart/store.json"]
    ports:
      - "10.10.40.77:3225:25"
      - "10.10.40.77:993:993"
      - "10.10.40.77:465:465"
    volumes:
      - /datapool/opt/praesidium-mail-corp/data:/opt/stalwart-mail
      - /datapool/opt/praesidium-mail-corp/config:/etc/stalwart:ro
      - /datapool/opt/praesidium/certs/praesidium.legal:/etc/certs/praesidium.legal:ro
    networks:
      praesidium-internal:
        ipv4_address: 172.28.0.28
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 10.10.10.1
      - 8.8.8.8
    environment:
      - TZ=America/Chicago
      - STALWART_HEALTHCHECK_URL=http://127.0.0.1:8080/healthz/live
      - STALWART_RECOVERY_ADMIN=admin:${RECOVERY_ADMIN_PASSWORD}
networks:
  praesidium-internal:
    name: praesidium-internal
    external: true
