"""Chat attachments — files dropped onto or generated by the AI assistant.

chat_attachments: one row per file associated with a chat session, so that
documents dropped onto any AI assistant (DMS files, local uploads, the
currently-open document) and documents the AI generates are all findable
later from chat history.

Revision ID: 0121_chat_attachments
Revises: 0120_deal_center_nav
"""
from alembic import op

revision = '0121_chat_attachments'
down_revision = '0120_deal_center_nav'


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS chat_attachments (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id       TEXT NOT NULL,
            session_id      UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
            matter_id       UUID REFERENCES matters(id),
            kind            TEXT NOT NULL DEFAULT 'dropped',
            source          TEXT,
            filename        TEXT NOT NULL,
            storage_path    TEXT,
            relative_path   TEXT,
            document_id     UUID,
            draft_id        UUID REFERENCES drafting_outputs(id) ON DELETE SET NULL,
            file_size       BIGINT,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_chat_attachments_session ON chat_attachments(session_id, created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_chat_attachments_tenant ON chat_attachments(tenant_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_chat_attachments_matter ON chat_attachments(matter_id)")


def downgrade():
    op.execute("DROP TABLE IF EXISTS chat_attachments CASCADE")
